services:
    database:
        image: postgres:16
        container_name: crm_postgres_local
        environment:
            POSTGRES_DB: crm_local
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "crm_local", "-U", "postgres"]
            timeout: 5s
            retries: 5
            start_period: 10s
        volumes:
            - db_data:/var/lib/postgresql/data:rw

volumes:
    db_data:
