<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260612145035 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE piece (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(255) NOT NULL, libelle VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, prix_vente NUMERIC(10, 2) DEFAULT NULL, prix_catalogue NUMERIC(10, 2) DEFAULT NULL, quantite_stock INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_44CA0B23AEA34913 ON piece (reference)');
        $this->addSql('CREATE TABLE piece_composition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, piece_parent_id INT NOT NULL, piece_enfant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F2AFB39642FB47F6 ON piece_composition (piece_parent_id)');
        $this->addSql('CREATE INDEX IDX_F2AFB396758CA8AF ON piece_composition (piece_enfant_id)');
        $this->addSql('ALTER TABLE piece_composition ADD CONSTRAINT FK_F2AFB39642FB47F6 FOREIGN KEY (piece_parent_id) REFERENCES piece (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE piece_composition ADD CONSTRAINT FK_F2AFB396758CA8AF FOREIGN KEY (piece_enfant_id) REFERENCES piece (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE piece_composition DROP CONSTRAINT FK_F2AFB39642FB47F6');
        $this->addSql('ALTER TABLE piece_composition DROP CONSTRAINT FK_F2AFB396758CA8AF');
        $this->addSql('DROP TABLE piece');
        $this->addSql('DROP TABLE piece_composition');
    }
}
