<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260623141346 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE devis (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_devis TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_limite TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, client_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8B27C52B19EB6921 ON devis (client_id)');
        $this->addSql('CREATE INDEX IDX_8B27C52BA76ED395 ON devis (user_id)');
        $this->addSql('CREATE TABLE devis_ligne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, prix NUMERIC(10, 2) NOT NULL, devis_id INT NOT NULL, piece_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_41D3C6A741DEFADA ON devis_ligne (devis_id)');
        $this->addSql('CREATE INDEX IDX_41D3C6A7C40FCFA8 ON devis_ligne (piece_id)');
        $this->addSql('ALTER TABLE devis ADD CONSTRAINT FK_8B27C52B19EB6921 FOREIGN KEY (client_id) REFERENCES client (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE devis ADD CONSTRAINT FK_8B27C52BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE devis_ligne ADD CONSTRAINT FK_41D3C6A741DEFADA FOREIGN KEY (devis_id) REFERENCES devis (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE devis_ligne ADD CONSTRAINT FK_41D3C6A7C40FCFA8 FOREIGN KEY (piece_id) REFERENCES piece (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE devis DROP CONSTRAINT FK_8B27C52B19EB6921');
        $this->addSql('ALTER TABLE devis DROP CONSTRAINT FK_8B27C52BA76ED395');
        $this->addSql('ALTER TABLE devis_ligne DROP CONSTRAINT FK_41D3C6A741DEFADA');
        $this->addSql('ALTER TABLE devis_ligne DROP CONSTRAINT FK_41D3C6A7C40FCFA8');
        $this->addSql('DROP TABLE devis');
        $this->addSql('DROP TABLE devis_ligne');
    }
}
