<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260625130442 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cmd_achat_ligne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, prix_achat NUMERIC(10, 2) NOT NULL, commande_achat_id INT NOT NULL, piece_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1B4FB12C28B5C98D ON cmd_achat_ligne (commande_achat_id)');
        $this->addSql('CREATE INDEX IDX_1B4FB12CC40FCFA8 ON cmd_achat_ligne (piece_id)');
        $this->addSql('CREATE TABLE commande_achat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_commande TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_prevue TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_reelle TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, fournisseur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1FC15B95670C757F ON commande_achat (fournisseur_id)');
        $this->addSql('CREATE TABLE fournisseur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, raison_sociale VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, telephone VARCHAR(20) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE cmd_achat_ligne ADD CONSTRAINT FK_1B4FB12C28B5C98D FOREIGN KEY (commande_achat_id) REFERENCES commande_achat (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cmd_achat_ligne ADD CONSTRAINT FK_1B4FB12CC40FCFA8 FOREIGN KEY (piece_id) REFERENCES piece (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commande_achat ADD CONSTRAINT FK_1FC15B95670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE piece ADD fournisseur_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE piece ADD CONSTRAINT FK_44CA0B23670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_44CA0B23670C757F ON piece (fournisseur_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cmd_achat_ligne DROP CONSTRAINT FK_1B4FB12C28B5C98D');
        $this->addSql('ALTER TABLE cmd_achat_ligne DROP CONSTRAINT FK_1B4FB12CC40FCFA8');
        $this->addSql('ALTER TABLE commande_achat DROP CONSTRAINT FK_1FC15B95670C757F');
        $this->addSql('DROP TABLE cmd_achat_ligne');
        $this->addSql('DROP TABLE commande_achat');
        $this->addSql('DROP TABLE fournisseur');
        $this->addSql('ALTER TABLE piece DROP CONSTRAINT FK_44CA0B23670C757F');
        $this->addSql('DROP INDEX IDX_44CA0B23670C757F');
        $this->addSql('ALTER TABLE piece DROP fournisseur_id');
    }
}
