<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260616072629 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE gamme_operation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ordre INT NOT NULL, gamme_id INT NOT NULL, operation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7608A5FBD2FD85F1 ON gamme_operation (gamme_id)');
        $this->addSql('CREATE INDEX IDX_7608A5FB44AC3583 ON gamme_operation (operation_id)');
        $this->addSql('CREATE TABLE machine (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE operation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) NOT NULL, temps_prevu INT NOT NULL, poste_machine_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1981A66D87A2FF14 ON operation (poste_machine_id)');
        $this->addSql('CREATE TABLE poste_machine (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, poste_id INT NOT NULL, machine_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_65BFFD14A0905086 ON poste_machine (poste_id)');
        $this->addSql('CREATE INDEX IDX_65BFFD14F6B75B26 ON poste_machine (machine_id)');
        $this->addSql('CREATE TABLE poste_travail (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE qualification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, poste_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B712F0CEA76ED395 ON qualification (user_id)');
        $this->addSql('CREATE INDEX IDX_B712F0CEA0905086 ON qualification (poste_id)');
        $this->addSql('CREATE TABLE realisation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, gamme_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EAA5610ED2FD85F1 ON realisation (gamme_id)');
        $this->addSql('CREATE TABLE realisation_poste (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, temps INT NOT NULL, realisation_id INT NOT NULL, gamme_operation_id INT NOT NULL, poste_machine_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B62960FBB685E551 ON realisation_poste (realisation_id)');
        $this->addSql('CREATE INDEX IDX_B62960FB27B99E9 ON realisation_poste (gamme_operation_id)');
        $this->addSql('CREATE INDEX IDX_B62960FB87A2FF14 ON realisation_poste (poste_machine_id)');
        $this->addSql('ALTER TABLE gamme_operation ADD CONSTRAINT FK_7608A5FBD2FD85F1 FOREIGN KEY (gamme_id) REFERENCES gamme (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE gamme_operation ADD CONSTRAINT FK_7608A5FB44AC3583 FOREIGN KEY (operation_id) REFERENCES operation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE operation ADD CONSTRAINT FK_1981A66D87A2FF14 FOREIGN KEY (poste_machine_id) REFERENCES poste_machine (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE poste_machine ADD CONSTRAINT FK_65BFFD14A0905086 FOREIGN KEY (poste_id) REFERENCES poste_travail (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE poste_machine ADD CONSTRAINT FK_65BFFD14F6B75B26 FOREIGN KEY (machine_id) REFERENCES machine (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE qualification ADD CONSTRAINT FK_B712F0CEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE qualification ADD CONSTRAINT FK_B712F0CEA0905086 FOREIGN KEY (poste_id) REFERENCES poste_travail (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE realisation ADD CONSTRAINT FK_EAA5610ED2FD85F1 FOREIGN KEY (gamme_id) REFERENCES gamme (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE realisation_poste ADD CONSTRAINT FK_B62960FBB685E551 FOREIGN KEY (realisation_id) REFERENCES realisation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE realisation_poste ADD CONSTRAINT FK_B62960FB27B99E9 FOREIGN KEY (gamme_operation_id) REFERENCES gamme_operation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE realisation_poste ADD CONSTRAINT FK_B62960FB87A2FF14 FOREIGN KEY (poste_machine_id) REFERENCES poste_machine (id) NOT DEFERRABLE');
        $this->addSql('DROP INDEX uniq_44ca0b23aea34913');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE gamme_operation DROP CONSTRAINT FK_7608A5FBD2FD85F1');
        $this->addSql('ALTER TABLE gamme_operation DROP CONSTRAINT FK_7608A5FB44AC3583');
        $this->addSql('ALTER TABLE operation DROP CONSTRAINT FK_1981A66D87A2FF14');
        $this->addSql('ALTER TABLE poste_machine DROP CONSTRAINT FK_65BFFD14A0905086');
        $this->addSql('ALTER TABLE poste_machine DROP CONSTRAINT FK_65BFFD14F6B75B26');
        $this->addSql('ALTER TABLE qualification DROP CONSTRAINT FK_B712F0CEA76ED395');
        $this->addSql('ALTER TABLE qualification DROP CONSTRAINT FK_B712F0CEA0905086');
        $this->addSql('ALTER TABLE realisation DROP CONSTRAINT FK_EAA5610ED2FD85F1');
        $this->addSql('ALTER TABLE realisation_poste DROP CONSTRAINT FK_B62960FBB685E551');
        $this->addSql('ALTER TABLE realisation_poste DROP CONSTRAINT FK_B62960FB27B99E9');
        $this->addSql('ALTER TABLE realisation_poste DROP CONSTRAINT FK_B62960FB87A2FF14');
        $this->addSql('DROP TABLE gamme_operation');
        $this->addSql('DROP TABLE machine');
        $this->addSql('DROP TABLE operation');
        $this->addSql('DROP TABLE poste_machine');
        $this->addSql('DROP TABLE poste_travail');
        $this->addSql('DROP TABLE qualification');
        $this->addSql('DROP TABLE realisation');
        $this->addSql('DROP TABLE realisation_poste');
        $this->addSql('CREATE UNIQUE INDEX uniq_44ca0b23aea34913 ON piece (reference)');
    }
}
